### ISSUE TITLE
Crashes on Some Android devices

### ISSUE THREAD

**Issue by dill0wn** [matyasf/zbar-ane#4]
When testing on an Android Droid Razr Maxx running Android 4.1.2, the app hard crashes when I try to open the scanner.  It has a back facing camera, and all the xml permissions seem to be set up correctly.  Other than on this one device  (and the Nexus 7 we have), the ane works great!  Great Work!

Looking at the adb logcat, the only thing seemingly relevant is this:

05-23 15:20:39.078  2362  2362 E AndroidRuntime: FATAL EXCEPTION: main
05-23 15:20:39.078  2362  2362 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{air.com.gvsulibrary.libraryquest.debug/com.blogspot.visualscripts.activity.CodeReaderActivity}: java.lang.RuntimeException: autoFocus failed
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2136)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.ActivityThread.access$700(ActivityThread.java:141)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:137)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5059)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:511)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)
05-23 15:20:39.078  2362  2362 E AndroidRuntime: Caused by: java.lang.RuntimeException: autoFocus failed
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.hardware.Camera.native_autoFocus(Native Method)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.hardware.Camera.autoFocus(Camera.java:918)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at com.blogspot.visualscripts.activity.CodeReaderActivity.onCreate(CodeReaderActivity.java:95)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:5058)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
05-23 15:20:39.078  2362  2362 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)

**Comment by matyasf** [comment]
thanks for the report! it seems, that some devices (that dont have autofocus?), throw an exception on line 95 in CodeReaderActivity:
 mCamera.autoFocus(autoFocusCB);

**Comment by CoIin** [comment]
Did you ever do something about this? I'm try the ANE with Google Glass, and it immediately shows a "scanner stopped working" kind of message. It too doesn't have an auto focus, so this is likely to be the same problem.

I have used two other approaches, one being ActionScript only, which works but is sideways and low frame rate. The other one is native, but the video is sideways and skewed. I was hoping that your one would do better than that, but it won't even start the scan.

**Comment by CoIin** [comment]
We managed to put the autoFocus lines into a try/catch, and have a .jar file, but the instructions on how to package that into an ANE are fairly complex! Would you be willing to do an update to the ANE, with the autoFocus calls in a try/catch?

**Comment by matyasf** [comment]
This should be fixed, try to download the latest .ANE

**Comment by CoIin** [comment]
Thanks, I'll give it a try. My Google Glass is at work, I'll try tomorrow. I did recently buy the Distriqt scanner ANE, but only found out afterwards that it too required auto focus.

**Comment by matyasf** [comment]
I have included a test android app, you can use it to test quickly if it works. its at https://github.com/matyasf/zbar-ane/blob/master/java/bin/ZbarANE.apk

**Comment by CoIin** [comment]
I tried the app you made, and could side load the APK ok, but then couldn't find it in the list of apps in order to launch it. I did do my own AIR test, and could see the Scanning/Cancel buttons on top of the video, but unfortunately the video is rotated 90 degrees. The width and height are remaining normal though, which means the rotated image looks squished. I tried as landscape and portrait, but still the image was rotated. Could it be that your code is assuming devices can do portrait? Google Glass is landscape only.

That aside, it did scan! Even without me having to tilt my head.

**Comment by matyasf** [comment]
>  Could it be that your code is assuming devices can do portrait?       

yes, it forces to view to go to portrait mode. I can make automatically rotate.
As for the cancel button: how do you cancel with a google glass? i guess you cant click on the glass..

**Comment by CoIin** [comment]
I didn't yet figure out the touch events, they don't seem to get passed through from Glass. I set the scanner going on ADDED_TO_STAGE at the moment.

**Comment by matyasf** [comment]
I have pushed a change, now it should auto rotate. Note that the manifest.xml changed a bit, you dont need to have CodeReaderActivity added there
